In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
n_sample = 1001
n_highdim = 992
np.random.seed(42)

In [3]:
if not os.path.exists('./data'):
    os.makedirs('./data')

In [4]:
ma = np.random.randint(1, 150, size=(1,n_sample))[0]
a = np.random.randint(-20, 120, size=(1,n_sample))[0]
b = np.random.randint(0, 160, size=(1,n_sample))[0]

In [5]:
df_name = pd.DataFrame(data=np.vstack([ma, a, b]).T, columns=['ma', 'a', 'b'])
df_name['name'] = [f'ma{ma[i]}a{a[i]}b{b[i]}' for i in range(0, n_sample)]

In [6]:
df_name

       ma   a    b          name
0     103  57   87   ma103a57b87
1      93  94   68    ma93a94b68
2      15  92  159   ma15a92b159
3     107  93   86   ma107a93b86
4      72  42  100   ma72a42b100
...   ...  ..  ...           ...
996    30   7   12     ma30a7b12
997   144  13   20   ma144a13b20
998    19 -13  146  ma19a-13b146
999    18  58   52    ma18a58b52
1000    1  66   18     ma1a66b18

[1001 rows x 4 columns]

In [7]:
df_name.to_csv('./data/df_name_points.csv', index=False)

In [8]:
data_high = np.random.randn(n_sample, n_highdim)
df_highdim = pd.DataFrame(data=data_high)
df_highdim['name'] = df_name['name']
df_highdim

,0,1,2,3,4,5,6,7,8,9,...,983,984,985,986,987,988,989,990,991,name
0,-0.854673,0.335037,0.007964,1.003710,2.187489,-1.290364,-0.648914,0.189092,-1.105353,0.782183,...,-1.301344,0.484447,0.461666,-0.792209,-2.236329,0.410762,-0.186803,0.336071,1.957175,ma103a57b87
1,-0.026832,-0.513839,-1.147322,-0.312422,0.160577,0.053307,1.723465,0.499086,-0.134801,-0.706561,...,1.704651,2.390766,0.377092,-0.099970,-1.595637,-0.760418,-0.126736,-0.715063,-0.609901,ma93a94b68
2,1.575389,0.028791,0.118212,-0.674191,1.177545,-0.212579,-0.520864,-1.580751,-0.061102,-0.552058,...,-0.960129,0.144908,0.280963,1.857929,0.970805,0.084106,-0.335207,3.014712,0.626595,ma15a92b159
3,-0.668752,-0.224623,-0.877455,-2.404550,0.312651,1.782454,-1.630557,0.055263,-0.706905,0.521503,...,1.212368,0.094279,-1.036365,-0.830622,1.762128,0.165489,1.746154,0.498605,0.753736,ma107a93b86
4,0.938724,-1.223139,0.306951,-1.236999,-0.284912,0.640170,-1.025334,0.559337,-1.498369,1.143320,...,-0.647377,0.690925,0.017970,0.003961,-0.591444,0.770022,0.154344,0.096744,-0.593421,ma72a42b100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,-0.690793,-0.096597,-0.846955,0.407375,-1.517757,-0.371745,0.339412,0.091350,-1.256910,-1.442045,...,-0.150086,0.343137,2.943809,-0.881613,1.808931,0.874224,2.100874,-0.616516,0.680243,ma30a7b12
997,-0.022643,-0.947541,-1.501941,1.742411,-0.488502,0.160649,0.362362,-0.893426,-2.004234,-1.071192,...,-1.143941,-0.542076,0.411015,0.478754,-0.412863,0.066329,-0.100634,1.587722,-0.400096,ma144a13b20
998,-0.763354,-1.448062,0.005283,0.168419,-1.169173,-0.875378,-1.128370,-0.309630,0.166051,-1.475045,...,-0.910382,1.483986,1.217189,1.560890,-1.509946,0.061478,0.489314,-0.298660,-0.376223,ma19a-13b146
999,-1.455376,0.705792,0.374877,-0.830782,-0.595886,0.475882,1.699735,-1.274484,-0.397510,-0.103900,...,-0.502000,-0.593411,0.502202,-0.540282,-0.232462,-0.621870,1.156374,0.717022,0.102821,ma18a58b52
1000,1.155900,0.246357,-0.271511,1.074804,0.147991,0.038195,-1.178136,-0.232895,1.523542,-1.752560,...,-0.845445,0.439096,0.403352,-1.283714,1.691898,-0.568469,1.222898,0.521256,0.570146,ma1a66b18

In [9]:
df_highdim.to_csv('./data/df_highdim_points.csv', index=False)